### ISSUE TITLE
Wine version winetricks recipe for keygen / patcher

### ISSUE THREAD

**Issue by salaros** [DoubleLabyrinth/navicat-keygen#148]
As far as I can see from issues people have been able to run your keygen/ patcher on Linux using Wine
Is there any guide on what's the best version of Wine to use and / or libraries to install via [winetricks](https://wiki.winehq.org/Winetricks)?

P.S. Thanks for such an awesome project!

**Comment by DoubleLabyrinth** [comment]
Sorry for late response. (I thought there would be someone who can respond you.)

I don't know what the best version of Wine is. But the latest Wine is just ok. 
As for libraries , I don't think you have to install some extra libraries because I have already build this keygen staticly. It sould not have dependency on libraries such as openssl, CRT, etc.

**Comment by salaros** [comment]
Hm... I think that some encryption-related library is missing from ~/.navicat prefix created by Navicat itself

```bash
Your name: -
Your organization: -

Input request code (in Base64), input empty line to end:
QlPp90IpR8KQxEEiL8+rShU2JOQVCeZtAUGbRw6JhzGI3w+t0OHuZ3UQG6A/4v80gkBqM+PYi68p
IkQBPBj1/vr9nj5FOxOPFWgnPEKzvvwE5WFLsKtHdjY+maQvMIQHiwthNtOTyj8YLqMCDwoahZ7r
szG8ZrTNjKVXe2T/N1ilbj1RyEyxJDYiIGx2A1/whBixTsRlixnOAjIfwurcT8vAx9+ZriEbE7Sy
uzYtCY00N+IyTNQl5mSgGZE4s65Ydq/jzAgATzv4EJ45H8pRx9T2U2qCAfCI30u611nMufEC4mCs
IMMXKSEGezXwpvIPoXDuZd+q6i/jqMbTGEhuLA==

fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
@Function: void __cdecl Process(class RSACipher *,int,int) LINE: 212
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ver:GetCurrentPackageId (0x32fdb4 (nil)): stub
```
