### ISSUE TITLE
MacOs 2013 - Lost connection to MySQL server at 'reading initial communication packet'

### ISSUE THREAD

**Issue by yanqi321** [DoubleLabyrinth/navicat-keygen#257]
+ Navicat Premium
+ Navicat version: 12.1.08
+ Simplified Chinese
+ macOS
+ console output:
```
2013 - Lost connection to MySQL server at 'reading initial communication packet', system error: 0 "Internal error/check (Not system error)", Time: 0.000000s
```
I can successfully register my navicat. but  it  Lost connection when i switch to another window(task) for a while. i need to reconnect the database again;
can you help me? thank you

**Comment by DoubleLabyrinth** [comment]
I don't think it is the problem caused by navicat-patcher. Maybe it is a bug from Navicat itself.

**Comment by Tampa** [comment]
Hate to dig this up, but the problem was introduced in version 12 and up of Navicat, my version 11 never fails to connect on 12 and 15 connecting to databases sometimes works and sometimes consistently fails with that very error. I searched around, but could not find anything related directly to a Navicat bug and tried all the suggestions for database configuration and server setup, no avail. So I guess this is my last stop before simply sticking to version 11. @DoubleLabyrinth
